#!/bin/bash

echo "Content-Type: text/html"
echo ""
echo "<!DOCTYPE html>"
echo "<html><head><title>System Info</title></head><body>"
echo "<h1>🖥️ System Information</h1>"
echo "<p><strong>Date:</strong> $(date)</p>"
echo "<p><strong>Uptime:</strong> $(uptime)</p>"
echo "<p><strong>User:</strong> $(whoami)</p>"
echo "<p>Generated by Bash CGI script</p>"
echo "<a href='/'>← Back to Home</a>"
echo "</body></html>"
