#!/usr/bin/python3

import datetime
import os

print("Content-Type: text/html\r")
print("\r")
print("""<!DOCTYPE html>
<html>
<head>
    <title>Current Time - CGI</title>
    <style>
        body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
        .time { font-size: 2em; color: #5a67d8; }
    </style>
</head>
<body>
    <h1>🕐 Current Server Time</h1>
    <div class="time">""")

now = datetime.datetime.now()
print(f"    {now.strftime('%Y-%m-%d %H:%M:%S')}")

print("""    </div>
    <p>Generated by Python CGI script</p>
    <a href="/">← Back to Home</a>
</body>
</html>""")
